name: juice-contracts-system-tests
on:
  pull_request:
    branches:
      - main
      - test/system-tests
  push:
    branches:
      - main
      - test/system-tests
jobs:
  forge-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: cat deployments/mainnet/JBETHPaymentTerminal.json